export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL';

export const MY_PRODUCT_LIST_REQUEST = 'MY_PRODUCT_LIST_REQUEST';
export const MY_PRODUCT_LIST_SUCCESS = 'MY_PRODUCT_LIST_SUCCESS';
export const MY_PRODUCT_LIST_FAIL = 'MY_PRODUCT_LIST_FAIL';

export const PRODUCT_UPDATE_SUCCESS_CHANGE = 'PRODUCT_UPDATE_SUCCESS_CHANGE'
export const PRODUCT_CREATE_SUCCESS_CHANGE = 'PRODUCT_CREATE_SUCCESS_CHANGE'

export const CONTENT_UPLOAD_REQUEST = 'CONTENT_UPLOAD_REQUEST';
export const CONTENT_UPLOAD_SUCCESS = 'CONTENT_UPLOAD_SUCCESS';
export const CONTENT_UPLOAD_FAIL = 'CONTENT_UPLOAD_FAIL';

export const CONTENT_UPLOAD_SUCCESS_CHANGE = 'CONTENT_UPLOAD_SUCCESS_CHANGE'
export const CONTENT_DELETE_SUCCESS_CHANGE = 'CONTENT_DELETE_SUCCESS_CHANGE'

export const CONTENT_DELETE_REQUEST = 'CONTENT_DELETE_REQUEST';
export const CONTENT_DELETE_SUCCESS = 'CONTENT_DELETE_SUCCESS';
export const CONTENT_DELETE_FAIL = 'CONTENT_DELETE_FAIL';

export const ALLOT_COURSE_REQUEST = 'ALLOT_COURSE_REQUEST';
export const ALLOT_COURSE_SUCCESS = 'ALLOT_COURSE_SUCCESS';
export const ALLOT_COURSE_FAIL = 'ALLOT_COURSE_FAIL';


export const SECTION_LIST_REQUEST = 'SECTION_LIST_REQUEST';
export const SECTION_LIST_SUCCESS = 'SECTION_LIST_SUCCESS';
export const SECTION_LIST_FAIL = 'SECTION_LIST_FAIL';


export const ENROLLED_LIST_REQUEST = 'ENROLLED_LIST_REQUEST';
export const ENROLLED_LIST_SUCCESS = 'ENROLLED_LIST_SUCCESS';
export const ENROLLED_LIST_FAIL = 'ENROLLED_LIST_FAIL';

export const ENROLLED_LIST_SUCCESS_CHANGE = 'ENROLLED_LIST_SUCCESS_CHANGE'