
export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST';
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL';

export const STUDENT_LIST_FOR_ENROLL_REQUEST = 'STUDENT_LIST_FOR_ENROLL_REQUEST';
export const STUDENT_LIST_FOR_ENROLL_SUCCESS = 'STUDENT_LIST_FOR_ENROLL_SUCCESS';
export const STUDENT_LIST_FOR_ENROLL_FAIL = 'STUDENT_LIST_FOR_ENROLL_FAIL';

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST';
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS';
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL';

export const STUDENT_CREATE_REQUEST = 'STUDENT_CREATE_REQUEST';
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS';
export const STUDENT_CREATE_FAIL = 'STUDENT_CREATE_FAIL';

export const STUDENT_EDIT_REQUEST = 'STUDENT_EDIT_REQUEST';
export const STUDENT_EDIT_SUCCESS = 'STUDENT_EDIT_SUCCESS';
export const STUDENT_EDIT_FAIL = 'STUDENT_EDIT_FAIL';

export const STUDENT_DELETE_REQUEST = 'STUDENT_DELETE_REQUEST';
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS';
export const STUDENT_DELETE_FAIL = 'STUDENT_DELETE_FAIL';

export const STUDENT_UPDATE_SUCCESS_CHANGE = 'STUDENT_UPDATE_SUCCESS_CHANGE'